# Generated by Django 4.2.3 on 2023-10-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_orderitem_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResponse',
            fields=[
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Success', models.BooleanField(default=False)),
                ('Status', models.IntegerField(blank=True, default=0, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
